apiVersion: v1
kind: ReplicationController
metadata:
  name: kumile
spec:
  replicas: 3
  selector:
    app: kumile
  template:
    metadata:
      labels:
        app: kumile
    spec:
      containers:
      - name: kumile
        image: sangmile/kumile
        ports:
        - name: http
          containerPort: 8080
        readinessProbe:
          exec:
            command:
            - ls
            - /var/ready