apiVersion: v1
kind: Pod
metadata:
  name: kumile-manual-v2
  labels:
    creation_method: manual
    env: prod
spec:
  containers:
  - image: sangmile/kumile
    name: kumile
    ports:
    - containerPort: 8080
      protocol: TCP
