apiVersion: v1
kind: ReplicationController
metadata:
  name: kumile-v1
spec:
  replicas: 3
  template:
    metadata:
      name: kumile
      labels:
        app: kumile
    spec:
      containers:
      - image: sangmile/kumile:v1
        name: nodejs
---
apiVersion: v1
kind: Service
metadata:
  name: kumile
spec:
  type: LoadBalancer
  selector:
    app: kumile
  ports:
  - port: 80
    targetPort: 8080
