apiVersion: apps/v1
kind: Deployment
metadata:
  name: kumile
spec:
  replicas: 3
  minReadySeconds: 30
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: kumile
  template:
    metadata:
      name: kumile
      labels:
        app: kumile
    spec:
      containers:
      - image: sangmile/kumile:v1
        name: nodejs
        readinessProbe:
          periodSeconds: 1
          httpGet:
            path: /
            port: 8080