apiVersion: apps/v1
kind: Deployment
metadata:
  name: kumile
spec:
  replicas: 3
  template:
    metadata:
      name: kumile
      labels:
        app: kumile
    spec:
      containers:
      - image: sangmile/kumile:v1
        name: nodejs
  selector:
    matchLabels:
      app: kumile
