apiVersion: v1
kind: ReplicationController
metadata:
  name: kumile-v2
spec:
  replicas: 3
  template:
    metadata:
      name: kumile
      labels:
        app: kumile
        deployment: v2
    spec:
      containers:
      - image: sangmile/kumile:v2
        name: nodejs
