apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongodb-pvc 
spec:
  storageClassName: gp2             # PVC는 사용자 정의 스토리지 클래스를 요청한다.
  resources:
    requests:
      storage: 1Gi
  accessModes:
    - ReadWriteOnce
