apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongodb-pvc           # 나중에 파드의 볼륨을 요청할 때 사용
spec:
  resources:
    requests:
      storage: 10Gi
  accessModes:
  - ReadWriteOnce
  storageClassName: ""         # 동적 프로비저닝